### ISSUE TITLE
Test Woocommerce plugin on Wordpress 5.3 and resolve styling bug

### ISSUE THREAD

**Issue by katenorquay** [abletech/addressfinder-woocommerce#32]
@nigelramsay do you have instructions for how to create a new Wordpress test server? 

@1mattramsay @josephleniston, just fyi I have moved this card up from the backlog because I tried our plugin on the new wordpress/woocommerce and there is a small styling bug which should be fixed as part of this story.

**Comment by nigelramsay** [comment]
Just added to the wiki:

https://github.com/abletech/wiki/blob/master/clients/addressfinder/addressfinder-woocommerce/testing.md
